# Generated by Django 4.2.23 on 2025-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_entry_is_public_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(default='Neutral', max_length=100),
            preserve_default=False,
        ),
    ]
