# Generated by Django 4.2.23 on 2025-09-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_entry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('excited', 'Excited'), ('relaxed', 'Relaxed'), ('tired', 'Tired'), ('confused', 'Confused'), ('bored', 'Bored'), ('love', 'Love')], default='neutral', max_length=20),
        ),
    ]
